Task 2: Sentiment Analysis using NLP Pipeline & ML Models

1. Import Libraries

In [94]:
import pandas as pd
import numpy as np
import re
import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

2. Download NLTK Data

In [95]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

3. Load Dataset

In [96]:
df = pd.read_csv("IMDB Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

4. Data Understanding

In [97]:
print("Shape:", df.shape)
print("\nClass Distribution:\n", df['sentiment'].value_counts())

Shape: (50000, 2)

Class Distribution:
 sentiment
positive    25000
negative    25000
Name: count, dtype: int64

5. Preprocessing Function

In [98]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^a-zA-Z]", " ", text)

    words = text.split()
    words = [w for w in words if w not in stop_words]
    words = [lemmatizer.lemmatize(w) for w in words]

    return " ".join(words)

6. Apply Preprocessing

In [99]:
df['clean_text'] = df['review'].apply(preprocess)
df.head()

,review,sentiment,clean_text
0,One of the other reviewers has mentioned that ...,positive,one reviewer mentioned watching oz episode hoo...
1,A wonderful little production. <br /><br />The...,positive,wonderful little production br br filming tech...
2,I thought this was a wonderful way to spend ti...,positive,thought wonderful way spend time hot summer we...
3,Basically there's a family where a little boy ...,negative,basically family little boy jake think zombie ...
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,petter mattei love time money visually stunnin...

7. Feature Engineering (TF-IDF)

In [100]:
tfidf = TfidfVectorizer(max_features=5000)
X = tfidf.fit_transform(df['clean_text'])
y = df['sentiment']

8. Train-Test Split

In [101]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

9. Logistic Regression

In [102]:
lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression()

10. Naive Bayes

In [103]:
nb = MultinomialNB()
nb.fit(X_train, y_train)

MultinomialNB()

11. Decision Tree

In [104]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

DecisionTreeClassifier()

12. Evaluation Function

In [105]:
def evaluate(model, name):
    y_pred = model.predict(X_test)

    print(f"\n{name} Performance")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(y_test, y_pred, average='weighted'))
    print("Recall:", recall_score(y_test, y_pred, average='weighted'))
    print("F1 Score:", f1_score(y_test, y_pred, average='weighted'))

13. Evaluate All Models

In [106]:
evaluate(lr, "Logistic Regression")
evaluate(nb, "Naive Bayes")
evaluate(dt, "Decision Tree")

Logistic Regression Performance
Accuracy: 0.8883
Precision: 0.8885439997036574
Recall: 0.8883
F1 Score: 0.888269404292489

Naive Bayes Performance
Accuracy: 0.8561
Precision: 0.8561424095931763
Recall: 0.8561
F1 Score: 0.8560872148211786

Decision Tree Performance
Accuracy: 0.7165
Precision: 0.716516469129118
Recall: 0.7165
F1 Score: 0.7165037564805194

14. Predict New Sentence

In [107]:
def predict_sentiment(text):
    clean = preprocess(text)
    vec = tfidf.transform([clean])
    return lr.predict(vec)[0]   # using best model

In [111]:
sentence = "This movie is worst"
result = predict_sentiment(sentence)

print(f"The sentiment of the sentence is: {result.capitalize()}")

The sentiment of the sentence is: Negative

In [110]:
sentence = "This movie is amazing"
result = predict_sentiment(sentence)

print(f"The sentiment of the sentence is: {result.capitalize()}")

The sentiment of the sentence is: Positive

 Model & Feature Insights

- Logistic Regression performed the best among all models.
- It gave higher accuracy and F1-score compared to Naive Bayes and Decision Tree.
- TF-IDF worked better than Bag of Words because it gives importance to meaningful words.

 Preprocessing & Learning

- Preprocessing improved model performance by removing noise.
- Steps like lowercasing, removing stopwords, and lemmatization helped clean the text.
- Machine learning models do not understand meaning, they learn patterns from data.

 Conclusion

- Successfully built an end-to-end NLP pipeline:
  Raw Text → Preprocessing → Feature Engineering → Model Training → Evaluation
- Logistic Regression with TF-IDF gave the best results.
- This project shows how text data can be converted into useful insights using NLP.